# -*- coding: utf-8 -*-
"""Probability Density Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ewkf2N_fq_6q6L2lcUZNzCtiIxfdwNkJ
"""

import pandas as pd

df = pd.read_csv("/content/data.csv", encoding="latin1", low_memory=False)
print(df.columns)

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

r = 102303254
a_r = 0.05 * (r % 7)
b_r = 0.3 * ((r % 5) + 1)

os.makedirs("results", exist_ok=True)

df = pd.read_csv("data.csv", encoding="latin1", low_memory=False)
df.columns = df.columns.str.strip()

no2_cols = [c for c in df.columns if "no2" in c.lower()]
if len(no2_cols) == 0:
    raise ValueError("NO2 column not found. Print df.columns to check the dataset.")
col = no2_cols[0]

x = pd.to_numeric(df[col], errors="coerce").dropna().values
z = x + a_r * np.sin(b_r * x)

mu = float(np.mean(z))
var = float(np.var(z))
lam = float(1 / (2 * var))
c = float(1 / np.sqrt(2 * np.pi * var))

result_df = pd.DataFrame([{
    "roll_number": r,
    "a_r": a_r,
    "b_r": b_r,
    "mu": mu,
    "variance": var,
    "lambda": lam,
    "c": c,
    "no2_column_used": col,
    "num_samples_used": len(z)
}])

result_df.to_csv("results/result_table.csv", index=False)

plt.figure()
plt.hist(z, bins=50, density=True)
xs = np.linspace(z.min(), z.max(), 500)
pdf = c * np.exp(-lam * (xs - mu) ** 2)
plt.plot(xs, pdf)
plt.title("Empirical PDF of z and Fitted Model")
plt.xlabel("z")
plt.ylabel("density")
plt.savefig("results/result_graph.png", dpi=200, bbox_inches="tight")
plt.close()

print("Saved: results/result_table.csv")
print("Saved: results/result_graph.png")
print("mu =", mu)
print("lambda =", lam)
print("c =", c)